### ISSUE TITLE
database file

### ISSUE THREAD

**Issue by momostafa** [DeadMerc/Instagram-Spammer-bot#1]
Hello,
Thank you for the nice script, could you please provide the database file and config file

Thanks

**Comment by DeadMerc** [comment]
Hello, not sure, i think this script now work now, need repair auth part

**Comment by momostafa** [comment]
Ok thank you Max, anyway nice work

**Comment by DeadMerc** [comment]
Yeah, previously its worked)

**Comment by momostafa** [comment]
How to contact you for some coding work

**Comment by DeadMerc** [comment]
add me skype maxom77711

**Comment by momostafa** [comment]
great thank you

**Comment by momostafa** [comment]
I didn't find maxom77711 on skype

**Comment by DeadMerc** [comment]
sorry, my fail,
maxon77711
try this pls

**Comment by momostafa** [comment]
thanks I added you

**Comment by hasnhasan** [comment]
Hello,
Thank you for the nice script, could you please provide the database file and config file

Thanks

**Comment by batuhanates0** [comment]
Hello,
Thank you for the nice script, could you please provide the database file and config file?

Thanks

**Comment by DeadMerc** [comment]
Sry for late response, this script dont work now, and i dont have DB file.
