### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by jaanavrt** [DeadMerc/Instagram-Spammer-bot#3]
Hello i would like to purchase from you a php script do u offer a programming services? for 200$
very small feature with instagram api
if u do i would be happy to work with u! do u have email or a telegram / skype?
thanks!

**Comment by DeadMerc** [comment]
Hi,

I have other projects at this moment, no, sorry.

Thanks, Max

**Comment by jaanavrt** [comment]
how about when u will have more free time? i would be happy working with u its really small project in instagram api. 
if not also then its ok
thanks!
